import mongoose from 'mongoose';

// Embedded feedback on a user's previous answer. Shown inline in the chat
// under the AI's reply. null on the opening AI turn (no answer to grade yet).
const feedbackSchema = new mongoose.Schema(
  {
    rating: { type: String, default: '' },  // "8/10 — Strong"
    tags: { type: String, default: '' },    // "✓ Complete · ✓ Accurate"
    great: { type: String, default: '' },
    sharper: { type: String, default: '' },
    score: { type: Number, min: 0, max: 10 }, // numeric portion of `rating`
  },
  { _id: false }
);

const messageSchema = new mongoose.Schema(
  {
    role: { type: String, enum: ['ai', 'user'], required: true },
    html: { type: String, required: true },
    feedback: { type: feedbackSchema, default: null },
  },
  { _id: true, timestamps: true }
);

const topicSchema = new mongoose.Schema(
  { name: { type: String, required: true }, done: { type: Boolean, default: false } },
  { _id: false }
);

// The final session report — generated by a second Gemini call when the
// session ends. Null while the session is active.
const reportSchema = new mongoose.Schema(
  {
    overallScore: { type: Number, min: 0, max: 10 },
    meta: { type: String, default: '' },
    radar: {
      labels: { type: [String], default: [] },
      you: { type: [Number], default: [] },
      target: { type: [Number], default: [] },
    },
    strengths: { type: [String], default: [] },
    growth: { type: [String], default: [] },
    nextSteps: {
      type: [
        new mongoose.Schema(
          {
            icon: { type: String, default: '' },
            title: { type: String, required: true },
            body: { type: String, default: '' },
          },
          { _id: false }
        ),
      ],
      default: [],
    },
  },
  { _id: false }
);

const interviewSessionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    setup: {
      mode: { type: String, default: 'text' },
      role: { type: String, default: 'sde' },
      round: { type: String, default: 'technical' },
      level: { type: String, default: 'fresher' },
      difficulty: { type: String, default: 'medium' },
    },
    state: { type: String, enum: ['active', 'ended'], default: 'active', index: true },
    messages: { type: [messageSchema], default: [] },
    topicsCovered: { type: [topicSchema], default: [] },

    questionsCovered: { type: Number, default: 0 },
    questionsTarget: { type: Number, default: 10 },

    // Rolling average of per-answer scores (0-10). Kept as (sum, count) so we
    // can update the average without re-scanning history.
    scoreSum: { type: Number, default: 0 },
    scoreCount: { type: Number, default: 0 },

    startedAt: { type: Date, default: Date.now },
    endedAt: { type: Date },
    report: { type: reportSchema, default: null },
    llmModel: { type: String, default: '' },
  },
  { timestamps: true }
);

// Only one active session per user at any time. Regular (non-active) sessions
// are unrestricted — users can have a history.
interviewSessionSchema.index(
  { userId: 1, state: 1 },
  { unique: true, partialFilterExpression: { state: 'active' } }
);

interviewSessionSchema.methods.liveScore = function liveScore() {
  if (this.scoreCount === 0) return 0;
  return Math.round((this.scoreSum / this.scoreCount) * 10) / 10;
};

interviewSessionSchema.methods.toPublic = function toPublic() {
  return {
    id: this._id.toString(),
    setup: this.setup,
    state: this.state,
    messages: this.messages.map((m) => ({
      id: m._id.toString(),
      role: m.role,
      html: m.html,
      feedback: m.feedback
        ? {
            rating: m.feedback.rating,
            tags: m.feedback.tags,
            great: m.feedback.great,
            sharper: m.feedback.sharper,
          }
        : null,
    })),
    topicsCovered: this.topicsCovered.map((t) => ({ name: t.name, done: t.done })),
    questionsCovered: this.questionsCovered,
    questionsTarget: this.questionsTarget,
    liveScore: this.liveScore(),
    startedAt: this.startedAt,
    endedAt: this.endedAt,
    report: this.report
      ? {
          overallScore: this.report.overallScore,
          meta: this.report.meta,
          radar: {
            labels: this.report.radar?.labels || [],
            you: this.report.radar?.you || [],
            target: this.report.radar?.target || [],
          },
          strengths: this.report.strengths || [],
          growth: this.report.growth || [],
          nextSteps: (this.report.nextSteps || []).map((n) => ({
            icon: n.icon,
            title: n.title,
            body: n.body,
          })),
        }
      : null,
  };
};

export const InterviewSession = mongoose.model('InterviewSession', interviewSessionSchema);
